[book]
title = "The Cargo Book"
authors = ["zzy"]
author = "Alex Crichton, Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"
src = "src"
multilingual = true

[build]
build-dir = "docs"

[output.html]
theme = "src/theme"
# default-theme = "rust"
curly-quotes = true
mathjax-support = true
# git_repository_url = "https://github.com/zzy/mdbook-docs-zh"
# git-repository-icon = "fa-code-fork"

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
